name: CI/CD

on:
  push:
    branches : [main]

jobs:
    merge-with-private:
        runs-on: ubuntu-latest
        name: Merge modified files with private Libraries

        steps:
        - name: Checkout Libraries-pub
          uses: actions/checkout@v2
          with:
            path: ./public

        - name: Checkout Libraries
          uses: actions/checkout@v2
          with: 
            repository: Lummetry/libraries
            token: ${{ secrets.ACTIONS_TOKEN }}
            path: ./private
            ref: develop

        - name: Copy files to the private repo
          run: |
            while IFS= read -r line; do
              directory="$(echo $line | cut -d'|' -f1)"
              directory="$(echo $directory | sed 's/ *$//g')"
              target="$(echo $line | cut -d'|' -f2)"
              target="$(echo $target | sed 's/ *$//g')"
              if [ "$directory" = "" ]; then
                directory="."
              fi

              if [ "$target" = "" ]; then
                target="*"
              fi

              echo "Copying target '$target' from directory '$directory'"
              mkdir -p ./private/$directory
              cp -R ./public/$directory/$target ./private/$directory
            done < ./private/.github/workflows/utils/public_files.txt

        - name: Push in Libraries
          run: |
            cd ./private
            if [[ "$(git status --porcelain)" != "" ]]; then
              git config user.name lummetry-team
              git config user.email tech@lummetry.ai
              git add .
              git commit -m "merge from public repo"
              git push
            fi
